# Defaults
timezone            : America/Chicago
source              : .
safe                : false
encoding            : "utf-8"

# https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml

title               : Cinema-Blue
author              : Cinema-Blue
markdown            : kramdown
