# Defaults
timezone            : America/Chicago
source              : .
safe                : false
encoding            : "utf-8"

# https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml

title               : JackAndChat
author              : Bv5t3r
markdown            : kramdown
